FROM python:3.12-slim-bookworm
RUN apt-get update && apt-get install -y --no-install-recommends docker.io iptables iproute2 conntrack && rm -rf /var/lib/apt/lists/*
RUN pip install --no-cache-dir Flask==3.1.2 requests==2.32.5 gunicorn==25.0.3
WORKDIR /app
COPY deploy/eh /app
ENV TZ=Europe/Dublin PYTHONDONTWRITEBYTECODE=1
